name = "Jinja Lua"
grammar = "jinja"
path_suffixes = ["lua.j2", "lua.jinja", "lua.jinja2"]
tab_size = 2
block_comment = { start = "{#", prefix = "", end = "#}", tab_size = 0 }
brackets = [
    { start = "{{", end = "}}", close = true, newline = false },
    { start = "{%", end = "%}", close = true, newline = false },
    { start = "{#", end = "#}", close = true, newline = false },
    { start = "(", end = ")", close = true, newline = false },
    { start = "[", end = "]", close = true, newline = true },
    { start = "{", end = "}", close = true, newline = true },
]
