name = "Jinja Systemd"
grammar = "jinja"
path_suffixes = ["link.j2", "link.jinja", "link.jinja2", "netdev.j2", "netdev.jinja", "netdev.jinja2", "network.j2", "network.jinja", "network.jinja2", "service.j2", "service.jinja", "service.jinja2", "socket.j2", "socket.jinja", "socket.jinja2", "device.j2", "device.jinja", "device.jinja2", "mount.j2", "mount.jinja", "mount.jinja2", "automount.j2", "automount.jinja", "automount.jinja2", "swap.j2", "swap.jinja", "swap.jinja2", "target.j2", "target.jinja", "target.jinja2", "path.j2", "path.jinja", "path.jinja2", "timer.j2", "timer.jinja", "timer.jinja2", "snapshot.j2", "snapshot.jinja", "snapshot.jinja2", "slice.j2", "slice.jinja", "slice.jinja2", "scope.j2", "scope.jinja", "scope.jinja2"]
tab_size = 2
block_comment = { start = "{#", prefix = "", end = "#}", tab_size = 0 }
autoclose_before = "}])>"
collapsed_placeholder = "{# ... #}"
brackets = [
    { start = "{{", end = "}}", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "{%", end = "%}", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "{#", end = "#}", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "(", end = ")", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "[", end = "]", close = true, newline = true, not_in = ["string", "comment"] },
    { start = '"', end = '"', close = true, newline = false, not_in = ["string", "comment"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
]
