name = "Jinja C++"
grammar = "jinja"
path_suffixes = ["cpp.j2", "cpp.jinja", "cpp.jinja2", "h.j2", "h.jinja", "h.jinja2", "hpp.j2", "hpp.jinja", "hpp.jinja2", "cc.j2", "cc.jinja", "cc.jinja2", "cxx.j2", "cxx.jinja", "cxx.jinja2"]
tab_size = 4
block_comment = { start = "{#", prefix = "", end = "#}", tab_size = 0 }
autoclose_before = "}])>"
collapsed_placeholder = "{# ... #}"
brackets = [
    { start = "{{", end = "}}", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "{%", end = "%}", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "{#", end = "#}", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "(", end = ")", close = true, newline = false, not_in = ["string", "comment"] },
    { start = "[", end = "]", close = true, newline = true, not_in = ["string", "comment"] },
    { start = '"', end = '"', close = true, newline = false, not_in = ["string", "comment"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string", "comment"] },
]
